# Generated by Django 3.0.4 on 2020-03-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品'},
        ),
    ]
